In [1]:
%matplotlib inline

import pandas as pd 
import matplotlib.pyplot as plt

In [127]:
df = pd.read_csv("almightysoma.csv")  #all awards

In [3]:
df[:10]

         category              publication                name  year
0  Beat-Reporting      The Washington Post         Dana Priest  2006
1  Beat-Reporting  The Wall Street Journal  Amy Dockser Marcus  2005
2  Beat-Reporting  The Wall Street Journal       Daniel Golden  2004
3  Beat-Reporting        The Baltimore Sun       Diana K. Sugg  2003
4  Beat-Reporting       The New York Times  Gretchen Morgenson  2002
5  Beat-Reporting       The New York Times  David Cay Johnston  2001
6  Beat-Reporting   St. Paul Pioneer Press     George Dohrmann  2000
7  Beat-Reporting        Los Angeles Times  Michael A. Hiltzik  1999
8  Beat-Reporting        Los Angeles Times       Chuck Philips  1999
9  Beat-Reporting       The New York Times    Linda Greenhouse  1998

In [4]:
for i in lendf
df[''] = df
    
df2['name'] = df2['name'].apply( lambda s: HumanName( s ) if not ( isinstance( s,float ) and isnan( s ) )  else s )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

#Adding New Column 'organizational'

if it is a group award, then the value is 'yes'.

if it is an individual award, then the value is 'no'.

if it is 'No Award', then 'none'.

In [129]:
df['organizational'] = 'not defined'

In [130]:
for i in range(len(df['name'])): 
    if df['name'][i] == df['publication'][i] and df['name'][i] != "No Award" :
        df['organizational'][i] = 'yes'
#         print i, df.ix[i]
#         print "================================================================================"
#         df['organizational'] = 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [131]:
df[df['organizational'] == 'yes']

,category,publication,name,year,organizational
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes
607,International-Reporting,None,None,1951,yes
918,Public-Service,The Post and Courier,The Post and Courier,2015,yes
919,Public-Service,The Guardian US,The Guardian US,2014,yes
920,Public-Service,The Washington Post,The Washington Post,2014,yes
921,Public-Service,Sun Sentinel,Sun Sentinel,2013,yes
922,Public-Service,The Philadelphia Inquirer,The Philadelphia Inquirer,2012,yes
923,Public-Service,Los Angeles Times,Los Angeles Times,2011,yes
924,Public-Service,Bristol (VA) Herald Courier,Bristol (VA) Herald Courier,2010,yes
926,Public-Service,The Washington Post,The Washington Post,2008,yes
927,Public-Service,The Wall Street Journal,The Wall Street Journal,2007,yes
928,Public-Service,The Times-Picayune,The Times-Picayune,2006,yes
929,Public-Service,Sun Herald,Sun Herald,2006,yes
930,Public-Service,Los Angeles Times,Los Angeles Times,2005,yes
933,Public-Service,The Boston Globe,The Boston Globe,2003,yes
934,Public-Service,The New York Times,The New York Times,2002,yes
935,Public-Service,The Oregonian,The Oregonian,2001,yes
937,Public-Service,The Washington Post,The Washington Post,1999,yes
938,Public-Service,Grand Forks (ND) Herald,Grand Forks (ND) Herald,1998,yes
939,Public-Service,The Times-Picayune,The Times-Picayune,1997,yes
943,Public-Service,The Virgin Islands Daily News,The Virgin Islands Daily News,1995,yes
944,Public-Service,Akron Beacon Journal,Akron Beacon Journal,1994,yes
945,Public-Service,The Miami Herald,The Miami Herald,1993,yes
946,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1992,yes
947,Public-Service,Des Moines Register,Des Moines Register,1991,yes
948,Public-Service,Washington (NC) Daily News,Washington (NC) Daily News,1990,yes
950,Public-Service,Anchorage Daily News,Anchorage Daily News,1989,yes
951,Public-Service,The Charlotte Observer,The Charlotte Observer,1988,yes
952,Public-Service,The Pittsburgh Press,The Pittsburgh Press,1987,yes
953,Public-Service,The Denver Post,The Denver Post,1986,yes
...,...,...,...,...,...
989,Public-Service,Miami Herald and Brooklyn Eagle,Miami Herald and Brooklyn Eagle,1951,yes
990,Public-Service,Chicago Daily News and St. Louis Post-Dispatch,Chicago Daily News and St. Louis Post-Dispatch,1950,yes
992,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1948,yes
993,Public-Service,Baltimore Sun,Baltimore Sun,1947,yes
994,Public-Service,The Scranton Times,The Scranton Times,1946,yes
995,Public-Service,Detroit Free Press,Detroit Free Press,1945,yes
996,Public-Service,The New York Times,The New York Times,1944,yes
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes
1011,Public-Service,New York Evening World,New York Evening World,1929,yes
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes
1016,Public-Service,New York World,New York World,1924,yes
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes
1018,Public-Service,New York World,New York World,1922,yes
1019,Public-Service,The Boston Post,The Boston Post,1921,yes
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes
1022,Public-Service,The New York Times,The New York Times,1918,yes

In [132]:
df[df['name'] == 'No Award']

,category,publication,name,year,organizational
149,Criticism,No Award,No Award,1992,not defined
214,Editorial-Cartooning,No Award,No Award,1973,not defined
222,Editorial-Cartooning,No Award,No Award,1965,not defined
227,Editorial-Cartooning,No Award,No Award,1960,not defined
251,Editorial-Cartooning,No Award,No Award,1936,not defined
264,Editorial-Cartooning,No Award,No Award,1923,not defined
295,Editorial-Writing,No Award,No Award,1993,not defined
309,Editorial-Writing,No Award,No Award,1981,not defined
359,Editorial-Writing,No Award,No Award,1935,not defined
362,Editorial-Writing,No Award,No Award,1932,not defined
364,Editorial-Writing,No Award,No Award,1930,not defined
374,Editorial-Writing,No Award,No Award,1921,not defined
376,Editorial-Writing,No Award,No Award,1919,not defined
576,International-Reporting,No Award,No Award,1977,not defined
883,National-Reporting,No Award,No Award,1951,not defined
912,Photography,No Award,No Award,1946,not defined
1010,Public-Service,No Award,No Award,1930,not defined
1015,Public-Service,No Award,No Award,1925,not defined
1020,Public-Service,No Award,No Award,1920,not defined
1023,Public-Service,No Award,No Award,1917,not defined
1051,Reporting,No Award,No Award,1928,not defined
1061,Reporting,No Award,No Award,1919,not defined
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,not defined

In [133]:
for i in range(len(df['name'])): 
    if df['name'][i] == 'No Award': 
        df['organizational'][i] = 'none'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [134]:
df[df['name'] == 'No Award']

,category,publication,name,year,organizational
149,Criticism,No Award,No Award,1992,none
214,Editorial-Cartooning,No Award,No Award,1973,none
222,Editorial-Cartooning,No Award,No Award,1965,none
227,Editorial-Cartooning,No Award,No Award,1960,none
251,Editorial-Cartooning,No Award,No Award,1936,none
264,Editorial-Cartooning,No Award,No Award,1923,none
295,Editorial-Writing,No Award,No Award,1993,none
309,Editorial-Writing,No Award,No Award,1981,none
359,Editorial-Writing,No Award,No Award,1935,none
362,Editorial-Writing,No Award,No Award,1932,none
364,Editorial-Writing,No Award,No Award,1930,none
374,Editorial-Writing,No Award,No Award,1921,none
376,Editorial-Writing,No Award,No Award,1919,none
576,International-Reporting,No Award,No Award,1977,none
883,National-Reporting,No Award,No Award,1951,none
912,Photography,No Award,No Award,1946,none
1010,Public-Service,No Award,No Award,1930,none
1015,Public-Service,No Award,No Award,1925,none
1020,Public-Service,No Award,No Award,1920,none
1023,Public-Service,No Award,No Award,1917,none
1051,Reporting,No Award,No Award,1928,none
1061,Reporting,No Award,No Award,1919,none
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none

In [135]:
df[df['name'] == "staff"]

                  category          publication   name  year organizational
410  Explanatory-Reporting  The New York Times   staff  2010    not defined

In [136]:
df.ix[410]

category          Explanatory-Reporting
publication         The New York Times
name                              staff
year                               2010
organizational              not defined
Name: 410, dtype: object

In [137]:
df[df['name'] == "Staff"]

,category,publication,name,year,organizational
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,not defined
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,not defined
35,Breaking-News-Photography,Associated Press,Staff,2005,not defined
39,Breaking-News-Photography,The New York Times,Staff,2002,not defined
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,not defined
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,not defined
44,Breaking-News-Reporting,The Denver Post,Staff,2013,not defined
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,not defined
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,not defined
48,Breaking-News-Reporting,The New York Times,Staff,2009,not defined
49,Breaking-News-Reporting,The Washington Post,Staff,2008,not defined
50,Breaking-News-Reporting,The Oregonian,Staff,2007,not defined
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,not defined
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,not defined
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,not defined
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,not defined
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,not defined
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,not defined
57,Breaking-News-Reporting,The Denver Post,Staff,2000,not defined
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,not defined
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,not defined
399,Explanatory-Journalism,The New York Times,Staff,1986,not defined
403,Explanatory-Reporting,The New York Times,Staff,2013,not defined
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,not defined
423,Explanatory-Reporting,The New York Times,Staff,2002,not defined
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,not defined
441,Feature-Photography,The New York Times,Staff,2002,not defined
450,Feature-Photography,Associated Press,Staff,1995,not defined
452,Feature-Photography,Associated Press,Staff,1993,not defined
516,General-News-Reporting,San Jose (CA) Mercury News,Staff,1990,not defined
...,...,...,...,...,...
697,Local-General-or-Spot-News-Reporting,Los Angeles Times,Staff,1966,not defined
721,Local-Investigative-Specialized-Reporting,Chicago Tribune,Staff,1976,not defined
722,Local-Investigative-Specialized-Reporting,Indianapolis Star,Staff,1975,not defined
724,Local-Investigative-Specialized-Reporting,The Sun Newspapers of Omaha,Staff,1973,not defined
748,Local-Reporting,The Patriot-News,Staff,2012,not defined
754,Local-Reporting,Detroit Free Press,Staff,2009,not defined
773,Local-Reporting;-Edition-Time,Fargo (ND) Forum,Staff,1958,not defined
774,Local-Reporting;-Edition-Time,Salt Lake (UT) Tribune,Staff,1957,not defined
777,Local-Reporting;-Edition-Time,Vicksburg (MS) Sunday Post-Herald,Staff,1954,not defined
800,National-Reporting,The New York Times,Staff,2010,not defined
802,National-Reporting,St. Petersburg Times,Staff,2009,not defined
809,National-Reporting,Los Angeles Times,Staff,2004,not defined
812,National-Reporting,The Washington Post,Staff,2002,not defined
813,National-Reporting,The New York Times,Staff,2001,not defined
814,National-Reporting,The Wall Street Journal,Staff,2000,not defined
815,National-Reporting,The New York Times,Staff,1999,not defined
819,National-Reporting,The Wall Street Journal,Staff,1997,not defined
835,National-Reporting,Miami Herald,Staff,1987,not defined
836,National-Reporting,The New York Times,Staff,1987,not defined
842,National-Reporting,The Boston Globe,Staff,1983,not defined
901,Photography,New York Daily News,Staff,1956,not defined
949,Public-Service,The Philadelphia Inquirer,Staff,1990,not defined
973,Public-Service,Louisville Courier-Journal,Staff,1967,not defined
1080,Spot-News-Photography,Associated Press,Staff,1992,not defined
1108,Spot-News-Reporting,Newsday,Staff,1997,not defined
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,not defined
1111,Spot-News-Reporting,The New York Times,Staff,1994,not defined
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,not defined
1113,Spot-News-Reporting,Newsday,Staff,1992,not defined
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,not defined

In [143]:
for i in range(len(df['name'])): 
    if df['name'][i] == 'Staff': 
        df['organizational'][i] = 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [144]:
df[df['name'] == "Staff"]

,category,publication,name,year,organizational
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes
35,Breaking-News-Photography,Associated Press,Staff,2005,yes
39,Breaking-News-Photography,The New York Times,Staff,2002,yes
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes
399,Explanatory-Journalism,The New York Times,Staff,1986,yes
403,Explanatory-Reporting,The New York Times,Staff,2013,yes
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes
423,Explanatory-Reporting,The New York Times,Staff,2002,yes
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes
441,Feature-Photography,The New York Times,Staff,2002,yes
450,Feature-Photography,Associated Press,Staff,1995,yes
452,Feature-Photography,Associated Press,Staff,1993,yes
516,General-News-Reporting,San Jose (CA) Mercury News,Staff,1990,yes
...,...,...,...,...,...
697,Local-General-or-Spot-News-Reporting,Los Angeles Times,Staff,1966,yes
721,Local-Investigative-Specialized-Reporting,Chicago Tribune,Staff,1976,yes
722,Local-Investigative-Specialized-Reporting,Indianapolis Star,Staff,1975,yes
724,Local-Investigative-Specialized-Reporting,The Sun Newspapers of Omaha,Staff,1973,yes
748,Local-Reporting,The Patriot-News,Staff,2012,yes
754,Local-Reporting,Detroit Free Press,Staff,2009,yes
773,Local-Reporting;-Edition-Time,Fargo (ND) Forum,Staff,1958,yes
774,Local-Reporting;-Edition-Time,Salt Lake (UT) Tribune,Staff,1957,yes
777,Local-Reporting;-Edition-Time,Vicksburg (MS) Sunday Post-Herald,Staff,1954,yes
800,National-Reporting,The New York Times,Staff,2010,yes
802,National-Reporting,St. Petersburg Times,Staff,2009,yes
809,National-Reporting,Los Angeles Times,Staff,2004,yes
812,National-Reporting,The Washington Post,Staff,2002,yes
813,National-Reporting,The New York Times,Staff,2001,yes
814,National-Reporting,The Wall Street Journal,Staff,2000,yes
815,National-Reporting,The New York Times,Staff,1999,yes
819,National-Reporting,The Wall Street Journal,Staff,1997,yes
835,National-Reporting,Miami Herald,Staff,1987,yes
836,National-Reporting,The New York Times,Staff,1987,yes
842,National-Reporting,The Boston Globe,Staff,1983,yes
901,Photography,New York Daily News,Staff,1956,yes
949,Public-Service,The Philadelphia Inquirer,Staff,1990,yes
973,Public-Service,Louisville Courier-Journal,Staff,1967,yes
1080,Spot-News-Photography,Associated Press,Staff,1992,yes
1108,Spot-News-Reporting,Newsday,Staff,1997,yes
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes
1113,Spot-News-Reporting,Newsday,Staff,1992,yes
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes

In [145]:
df[df["organizational"] == 'not defined']

,category,publication,name,year,organizational
0,Beat-Reporting,The Washington Post,Dana Priest,2006,not defined
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,not defined
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,not defined
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,not defined
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,not defined
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,not defined
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,not defined
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,not defined
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,not defined
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,not defined
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,not defined
11,Beat-Reporting,Newsday,Bob Keeler,1996,not defined
12,Beat-Reporting,The Boston Globe,David Shribman,1995,not defined
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,not defined
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,not defined
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,not defined
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,not defined
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,not defined
18,Beat-Reporting,The New York Times,Natalie Angier,1991,not defined
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,not defined
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,not defined
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,not defined
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,not defined
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,not defined
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,not defined
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,not defined
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,not defined
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,not defined
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,not defined
30,Breaking-News-Photography,The Des Moines Register,Mary Chind,2010,not defined
...,...,...,...,...,...
1090,Spot-News-Photography,Associated Press,Bill Foley,1983,not defined
1091,Spot-News-Photography,Associated Press,Ron Edmonds,1982,not defined
1092,Spot-News-Photography,Fort Worth (TX) Star-Telegram,Larry C. Price,1981,not defined
1093,Spot-News-Photography,Ettela'at,Jahangir Razmi,1980,not defined
1094,Spot-News-Photography,Pottstown (PA) Mercury,Thomas J. Kelly III,1979,not defined
1095,Spot-News-Photography,United Press International,John H. Blair,1978,not defined
1096,Spot-News-Photography,Boston Herald American,Stanley Forman,1977,not defined
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,not defined
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,not defined
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,not defined
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,not defined
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,not defined
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,not defined
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,not defined
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,not defined
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,not defined
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,not defined
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,not defined
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,not defined
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,not defined
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,not defined
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,not defined
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,not defined
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,not defined
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,not defined
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,not defined
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,not defined
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,not defined
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,not defined
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,not defined

In [146]:
len(df[df["organizational"] == 'not defined'])

928

In [147]:
for i in range(len(df)): 
    if df["organizational"][i] == 'not defined': 
        df["organizational"][i] = 'no'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [148]:
df[df["organizational"] == 'no']

,category,publication,name,year,organizational
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no
11,Beat-Reporting,Newsday,Bob Keeler,1996,no
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no
30,Breaking-News-Photography,The Des Moines Register,Mary Chind,2010,no
...,...,...,...,...,...
1090,Spot-News-Photography,Associated Press,Bill Foley,1983,no
1091,Spot-News-Photography,Associated Press,Ron Edmonds,1982,no
1092,Spot-News-Photography,Fort Worth (TX) Star-Telegram,Larry C. Price,1981,no
1093,Spot-News-Photography,Ettela'at,Jahangir Razmi,1980,no
1094,Spot-News-Photography,Pottstown (PA) Mercury,Thomas J. Kelly III,1979,no
1095,Spot-News-Photography,United Press International,John H. Blair,1978,no
1096,Spot-News-Photography,Boston Herald American,Stanley Forman,1977,no
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no

##Some hard to categorize

leave it as 'not defined'

In [94]:
df.ix[112] #awarded to all American journalists in war period 

#http://www.pulitzer.org/bycat/Correspondence

category          Correspondence
publication                 None
name                 Group Award
year                        1941
organizational                no
Name: 112, dtype: object

In [95]:
df["organizational"][112] = 'not define'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [96]:
df.ix[112]

category          Correspondence
publication                 None
name                 Group Award
year                        1941
organizational        not define
Name: 112, dtype: object

In [149]:
df

,category,publication,name,year,organizational
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no
11,Beat-Reporting,Newsday,Bob Keeler,1996,no
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no
...,...,...,...,...,...
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no
1108,Spot-News-Reporting,Newsday,Staff,1997,yes
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes
1113,Spot-News-Reporting,Newsday,Staff,1992,yes
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no

# Add new column 'gender'

use first name to estimate gender (Sex mechaine).

In [150]:
from nameparser import HumanName
import sexmachine.detector as gender
d = gender.Detector()

In [151]:
df['first_name'] = 'none'

In [139]:
#df['first_name'] = df['name'].apply(lambda s: str(s).split()[0])

https://pypi.python.org/pypi/SexMachine/

In [152]:
indie_df = df[df['organizational'] == 'no'] 
indie_df

,category,publication,name,year,organizational,first_name
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no,none
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no,none
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no,none
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no,none
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no,none
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no,none
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no,none
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no,none
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no,none
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no,none
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no,none
11,Beat-Reporting,Newsday,Bob Keeler,1996,no,none
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no,none
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no,none
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no,none
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no,none
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no,none
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no,none
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no,none
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no,none
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no,none
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no,none
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no,none
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no,none
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no,none
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no,none
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no,none
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no,none
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no,none
30,Breaking-News-Photography,The Des Moines Register,Mary Chind,2010,no,none
...,...,...,...,...,...,...
1090,Spot-News-Photography,Associated Press,Bill Foley,1983,no,none
1091,Spot-News-Photography,Associated Press,Ron Edmonds,1982,no,none
1092,Spot-News-Photography,Fort Worth (TX) Star-Telegram,Larry C. Price,1981,no,none
1093,Spot-News-Photography,Ettela'at,Jahangir Razmi,1980,no,none
1094,Spot-News-Photography,Pottstown (PA) Mercury,Thomas J. Kelly III,1979,no,none
1095,Spot-News-Photography,United Press International,John H. Blair,1978,no,none
1096,Spot-News-Photography,Boston Herald American,Stanley Forman,1977,no,none
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no,none
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no,none
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no,none
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no,none
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no,none
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no,none
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no,none
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no,none
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no,none
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no,none
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no,none
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no,none
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no,none
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no,none
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no,none
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no,none
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no,none
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no,none
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no,none
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no,none
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no,none
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no,none
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no,none

In [153]:
indie_df['first_name'] = indie_df['name'].apply(lambda s: str(s).split()[0])
indie_df
#df['first_name'] = df['name'].apply(lambda s: str(s).split()[0])

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,category,publication,name,year,organizational,first_name
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no,Dana
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no,Amy
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no,Daniel
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no,Diana
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no,Gretchen
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no,David
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no,George
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no,Michael
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no,Chuck
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no,Linda
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no,Byron
11,Beat-Reporting,Newsday,Bob Keeler,1996,no,Bob
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no,David
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no,Jim
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no,Eric
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no,Joseph
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no,Paul
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no,Deborah
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no,Natalie
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no,Tyler
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no,Muhammed
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no,Khalil
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no,Narciso
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no,Manu
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no,Rodrigo
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no,Massoud
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no,Ricky
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no,Nikki
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no,Carol
30,Breaking-News-Photography,The Des Moines Register,Mary Chind,2010,no,Mary
...,...,...,...,...,...,...
1090,Spot-News-Photography,Associated Press,Bill Foley,1983,no,Bill
1091,Spot-News-Photography,Associated Press,Ron Edmonds,1982,no,Ron
1092,Spot-News-Photography,Fort Worth (TX) Star-Telegram,Larry C. Price,1981,no,Larry
1093,Spot-News-Photography,Ettela'at,Jahangir Razmi,1980,no,Jahangir
1094,Spot-News-Photography,Pottstown (PA) Mercury,Thomas J. Kelly III,1979,no,Thomas
1095,Spot-News-Photography,United Press International,John H. Blair,1978,no,John
1096,Spot-News-Photography,Boston Herald American,Stanley Forman,1977,no,Stanley
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no,Neal
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no,Stanley
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no,Gerald
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no,Anthony
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no,Huynh
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no,Michel
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no,Horst
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no,John
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no,Steve
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no,Edward
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no,Rocco
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no,Robert
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no,Eddy
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no,Homer
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no,Mark
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no,Daniel
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no,Ira
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no,Laurence
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no,Edward
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no,Edward
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no,James
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no,Dewey
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no,Louis

In [154]:
df['first_name']  = indie_df['first_name']  #organizational = yes, first name cell will leave NaN

In [155]:
df[df['organizational'] == 'yes'] #Check

,category,publication,name,year,organizational,first_name
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN
...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN
1016,Public-Service,New York World,New York World,1924,yes,NaN
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN
1018,Public-Service,New York World,New York World,1922,yes,NaN
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN

Create new column "gender"

In [156]:
df['gender'] = 'not applied' #default is not applied

In [157]:
df

,category,publication,name,year,organizational,first_name,gender
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no,Dana,not applied
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no,Amy,not applied
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no,Daniel,not applied
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no,Diana,not applied
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no,Gretchen,not applied
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no,David,not applied
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no,George,not applied
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no,Michael,not applied
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no,Chuck,not applied
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no,Linda,not applied
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no,Byron,not applied
11,Beat-Reporting,Newsday,Bob Keeler,1996,no,Bob,not applied
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no,David,not applied
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no,Jim,not applied
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no,Eric,not applied
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no,Joseph,not applied
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no,Paul,not applied
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no,Deborah,not applied
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no,Natalie,not applied
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,not applied
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no,Tyler,not applied
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no,Muhammed,not applied
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no,Khalil,not applied
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no,Narciso,not applied
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no,Manu,not applied
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no,Rodrigo,not applied
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no,Massoud,not applied
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no,Ricky,not applied
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no,Nikki,not applied
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no,Carol,not applied
...,...,...,...,...,...,...,...
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no,Neal,not applied
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no,Stanley,not applied
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no,Gerald,not applied
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no,Anthony,not applied
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no,Huynh,not applied
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no,Michel,not applied
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no,Horst,not applied
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no,John,not applied
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no,Steve,not applied
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no,Edward,not applied
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no,Rocco,not applied
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,not applied
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no,Robert,not applied
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,not applied
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,not applied
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,not applied
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,not applied
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,not applied
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no,Eddy,not applied
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no,Homer,not applied
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no,Mark,not applied
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no,Daniel,not applied
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no,Ira,not applied
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no,Laurence,not applied
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no,Edward,not applied
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no,Edward,not applied
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no,James,not applied
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no,Dewey,not applied
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none,NaN,not applied
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no,Louis,not applied

In [158]:
df[(df['organizational'] == 'yes')]

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,not applied
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,not applied
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,not applied
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,not applied
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,not applied
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,not applied
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,not applied
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,not applied
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,not applied
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,not applied
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,not applied
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,not applied
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,not applied
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,not applied
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,not applied
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,not applied
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,not applied
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,not applied
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,not applied
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,not applied
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,not applied
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,not applied
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,not applied
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,not applied
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,not applied
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,not applied
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,not applied
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,not applied
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,not applied
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN,not applied
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,not applied
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,not applied
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,not applied
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,not applied
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,not applied
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,not applied
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,not applied
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,not applied
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,not applied
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,not applied
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,not applied
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,not applied
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,not applied
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,not applied
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,not applied
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,not applied
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,not applied
1016,Public-Service,New York World,New York World,1924,yes,NaN,not applied
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,not applied
1018,Public-Service,New York World,New York World,1922,yes,NaN,not applied
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,not applied
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,not applied
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,not applied
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,not applied
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,not applied
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,not applied
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,not applied
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,not applied
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,not applied
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,not applied

##Main

In [159]:
df['gender'] = df['first_name'].apply( lambda s: d.get_gender(s))

In [160]:
df[(df['organizational'] == 'yes')] #Sex machine evalute NaN as andy, should change to be 'not apply'

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,andy
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,andy
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,andy
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,andy
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,andy
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,andy
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,andy
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,andy
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,andy
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,andy
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,andy
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,andy
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,andy
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,andy
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,andy
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,andy
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,andy
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,andy
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,andy
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,andy
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,andy
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,andy
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,andy
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,andy
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,andy
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,andy
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,andy
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,andy
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,andy
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN,andy
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,andy
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,andy
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,andy
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,andy
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,andy
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,andy
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,andy
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,andy
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,andy
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,andy
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,andy
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,andy
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,andy
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,andy
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,andy
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,andy
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,andy
1016,Public-Service,New York World,New York World,1924,yes,NaN,andy
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,andy
1018,Public-Service,New York World,New York World,1922,yes,NaN,andy
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,andy
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,andy
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,andy
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,andy
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,andy
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,andy
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,andy
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,andy
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,andy
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,andy

In [65]:
# df.to_csv('categorization_inprocess.csv', sep=',', encoding='utf-8')

##fix some error

sex machine evaluate NaN as 'andy', those are organizational awards 

to get the number of true "andy", and then see whether there's a need to manually evaluate the gender

# <font color = red> UNSOLVED

In [166]:
df[df['organizational'] == 'yes']

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,andy
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,andy
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,andy
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,andy
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,andy
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,andy
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,andy
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,andy
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,andy
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,andy
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,andy
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,andy
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,andy
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,andy
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,andy
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,andy
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,andy
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,andy
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,andy
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,andy
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,andy
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,andy
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,andy
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,andy
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,andy
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,andy
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,andy
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,andy
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,andy
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN,andy
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,andy
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,andy
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,andy
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,andy
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,andy
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,andy
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,andy
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,andy
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,andy
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,andy
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,andy
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,andy
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,andy
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,andy
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,andy
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,andy
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,andy
1016,Public-Service,New York World,New York World,1924,yes,NaN,andy
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,andy
1018,Public-Service,New York World,New York World,1922,yes,NaN,andy
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,andy
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,andy
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,andy
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,andy
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,andy
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,andy
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,andy
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,andy
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,andy
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,andy

In [161]:
df[(df['gender'] == 'andy') & (df['organizational'] == 'yes')]#['gender'] #= 'not applied'

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,andy
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,andy
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,andy
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,andy
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,andy
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,andy
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,andy
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,andy
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,andy
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,andy
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,andy
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,andy
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,andy
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,andy
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,andy
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,andy
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,andy
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,andy
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,andy
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,andy
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,andy
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,andy
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,andy
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,andy
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,andy
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,andy
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,andy
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,andy
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,andy
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN,andy
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,andy
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,andy
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,andy
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,andy
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,andy
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,andy
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,andy
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,andy
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,andy
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,andy
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,andy
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,andy
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,andy
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,andy
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,andy
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,andy
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,andy
1016,Public-Service,New York World,New York World,1924,yes,NaN,andy
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,andy
1018,Public-Service,New York World,New York World,1922,yes,NaN,andy
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,andy
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,andy
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,andy
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,andy
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,andy
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,andy
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,andy
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,andy
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,andy
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,andy

In [ ]:
#df_gender['gender'] = df_gender['first_name'].apply( lambda s: d.get_gender(s))

In [162]:
print str(df['gender'][0])

female

In [203]:
#df_gender['gender'] = df_gender['first_name'].apply( lambda s: d.get_gender(s))

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

##Fix some wrong categories

In [71]:
df[df['first_name'] == 'Photo']

,category,publication,name,year,organizational,first_name,gender
41,Breaking-News-Photography,Rocky Mountain News,Photo Staff,2000,no,Photo,andy
446,Feature-Photography,Associated Press,Photo Staff,1999,no,Photo,andy
1072,Spot-News-Photography,Associated Press,Photo Staff,1999,no,Photo,andy
1082,Spot-News-Photography,The Tribune,Photo Staff,1990,no,Photo,andy

In [72]:
df['organizational'][41] = 'yes'
df['organizational'][446]= 'yes'
df['organizational'][1072]= 'yes'
df['organizational'][1082]= 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [73]:
print df['organizational'][41]
print df['organizational'][446]
print df['organizational'][1072]
print df['organizational'][1082]

yes
yes
yes
yes

In [74]:
df['first_name'][41] = 'No'
df['first_name'][446]= 'No'
df['first_name'][1072]= 'No'
df['first_name'][1082]= 'No'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [75]:
df[df['first_name'] == 'Photography']

,category,publication,name,year,organizational,first_name,gender
38,Breaking-News-Photography,Rocky Mountain News,Photography Staff,2003,no,Photography,andy
1088,Spot-News-Photography,The Register,Photography Staff,1985,no,Photography,andy

In [76]:
df['organizational'][38] = 'yes'
df['organizational'][1088]= 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app

In [77]:
df[df['first_name'] == 'Editorial']

,category,publication,name,year,organizational,first_name,gender
267,Editorial-Writing,The Oregonian,Editorial Staff,2014,no,Editorial,andy
289,Editorial-Writing,Daily News,Editorial Board,1999,no,Editorial,andy
678,Local-General-or-Spot-News-Reporting,Fort Wayne (IN) News-Sentinel,Editorial Staff,1983,no,Editorial,andy
778,Local-Reporting;-Edition-Time,Providence (RI) Journal and Evening Bulletin,Editorial Staff,1953,no,Editorial,andy

In [78]:
df['organizational'][267] = 'yes'
df['organizational'][289]= 'yes'
df['organizational'][678]= 'yes'
df['organizational'][778]= 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [79]:
df[df['first_name'] == 'Staff']

,category,publication,name,year,organizational,first_name,gender
467,Feature-Photography,Boston Herald American,Staff Photographers,1979,no,Staff,andy

In [80]:
df['organizational'][467] = 'yes'

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [81]:
df[df['organizational'] == 'yes']

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,andy
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,andy
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,andy
38,Breaking-News-Photography,Rocky Mountain News,Photography Staff,2003,yes,Photography,andy
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,andy
41,Breaking-News-Photography,Rocky Mountain News,Photo Staff,2000,yes,No,andy
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,andy
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,andy
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,andy
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,andy
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,andy
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,andy
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,andy
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,andy
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,andy
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,andy
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,andy
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,andy
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,andy
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,andy
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,andy
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,andy
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,andy
267,Editorial-Writing,The Oregonian,Editorial Staff,2014,yes,Editorial,andy
289,Editorial-Writing,Daily News,Editorial Board,1999,yes,Editorial,andy
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,andy
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,andy
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,andy
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,andy
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,andy
...,...,...,...,...,...,...,...
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,andy
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,andy
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,andy
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,andy
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,andy
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,andy
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,andy
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,andy
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,andy
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,andy
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,andy
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,andy
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,andy
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,andy
1016,Public-Service,New York World,New York World,1924,yes,NaN,andy
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,andy
1018,Public-Service,New York World,New York World,1922,yes,NaN,andy
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,andy
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,andy
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,andy
1072,Spot-News-Photography,Associated Press,Photo Staff,1999,yes,No,andy
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,andy
1082,Spot-News-Photography,The Tribune,Photo Staff,1990,yes,No,andy
1088,Spot-News-Photography,The Register,Photography Staff,1985,yes,Photography,andy
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,andy
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,andy
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,andy
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,andy
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,andy
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,andy

In [259]:
df[(df['first_name'].notnull()) & (df['organizational'] == 'yes')]

# http://pandas.pydata.org/pandas-docs/stable/missing_data.html

,category,publication,name,year,organizational,first_name,gender
38,Breaking-News-Photography,Rocky Mountain News,Photography Staff,2003,yes,Photography,andy
41,Breaking-News-Photography,Rocky Mountain News,Photo Staff,2000,yes,No,andy
267,Editorial-Writing,The Oregonian,Editorial Staff,2014,yes,Editorial,andy
289,Editorial-Writing,Daily News,Editorial Board,1999,yes,Editorial,andy
446,Feature-Photography,Associated Press,Photo Staff,1999,yes,No,andy
467,Feature-Photography,Boston Herald American,Staff Photographers,1979,yes,Staff,andy
678,Local-General-or-Spot-News-Reporting,Fort Wayne (IN) News-Sentinel,Editorial Staff,1983,yes,Editorial,andy
778,Local-Reporting;-Edition-Time,Providence (RI) Journal and Evening Bulletin,Editorial Staff,1953,yes,Editorial,andy
1072,Spot-News-Photography,Associated Press,Photo Staff,1999,yes,No,andy
1082,Spot-News-Photography,The Tribune,Photo Staff,1990,yes,No,andy
1088,Spot-News-Photography,The Register,Photography Staff,1985,yes,Photography,andy

#Summary (temp)

In [82]:
df['publication'].value_counts()

The New York Times                            109
The Washington Post                            66
Associated Press                               51
Los Angeles Times                              49
The Wall Street Journal                        39
The Boston Globe                               37
Chicago Tribune                                29
No Award                                       28
The Philadelphia Inquirer                      25
Newsday                                        21
The Miami Herald                               18
St. Louis Post-Dispatch                        16
The Seattle Times                              15
The Dallas Morning News                        15
The Baltimore Sun                              13
Detroit Free Press                             13
New York Daily News                            12
Chicago Daily News                             12
Chicago Sun-Times                              11
The Denver Post                                 9
New York World                                  9
The Oregonian                                   8
United Press International                      7
Milwaukee Journal Sentinel                      7
The New York Times                              7
The Christian Science Monitor                   6
New York Herald Tribune                         6
Des Moines Register                             6
St. Petersburg (FL) Times                       6
Star Tribune                                    6
                                             ...
Xenia (OH) Daily Gazette                        1
the Chicago Tribune                             1
Gainesville (FL) Sun                            1
New York World-Telegram & Sun                   1
Flint (MI) Journal                              1
Vicksburg (MS) Sunday Post-Herald               1
Jackson (MI) Citizen Patriot                    1
The Guardian US                                 1
a syndicated columnist                          1
Chambersburg (Pennsylvania) Public Opinion      1
The Boston Post                                 1
The Daily Tribune                               1
The Providence Journal-Bulletin                 1
Daily Oklahoman                                 1
The Alabama Journal                             1
The Toronto Star                                1
Asbury Park Press                               1
The Riverdale (NY) Press                        1
North American Newspaper Alliance, Inc.         1
San Francisco Call-Bulletin                     1
Ettela'at                                       1
Investor's Business Daily                       1
Newark Evening News                             1
Baltimore Evening Suncategory                   1
Washington (DC) Daily News                      1
Miami Daily News                                1
Louisville (KY) Times                           1
The Orange County Register                      1
Dayton (OH) Daily News                          1
Newsday Syndicate                               1
dtype: int64

In [83]:
df['gender'].value_counts()

male             669
andy             294
female           113
mostly_male       29
mostly_female     22
dtype: int64

In [167]:
#female winners #135 rows 

df[(df['organizational'] == 'no') & (df['gender'] == 'female') | (df['gender'] == 'mostly_female')] #.value_counts()

,category,publication,name,year,organizational,first_name,gender
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no,Dana,female
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no,Amy,female
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no,Diana,female
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no,Gretchen,female
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no,Linda,female
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no,Deborah,female
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no,Natalie,female
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no,Nikki,female
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no,Carol,mostly_female
30,Breaking-News-Photography,The Des Moines Register,Mary Chind,2010,no,Mary,mostly_female
36,Breaking-News-Photography,The Dallas Morning News,Cheryl Diaz Meyer,2004,no,Cheryl,female
60,Commentary,Houston Chronicle,Lisa Falkenberg,2015,no,Lisa,female
63,Commentary,the Chicago Tribune,Mary Schmich,2012,no,Mary,mostly_female
65,Commentary,The Washington Post,Kathleen Parker,2010,no,Kathleen,female
68,Commentary,The Atlanta Journal-Constitution,Cynthia Tucker,2007,no,Cynthia,female
70,Commentary,The Plain Dealer,Connie Schultz,2005,no,Connie,mostly_female
74,Commentary,The Wall Street Journal,Dorothy Rabinowitz,2001,no,Dorothy,female
76,Commentary,The New York Times,Maureen Dowd,1999,no,Maureen,female
78,Commentary,The Boston Globe,Eileen McNamara,1997,no,Eileen,female
82,Commentary,The Miami Herald,Liz Balmaseda,1993,no,Liz,female
83,Commentary,The New York Times,Anna Quindlen,1992,no,Anna,female
95,Commentary,The Boston Globe,Ellen H. Goodman,1980,no,Ellen,female
100,Commentary,The Washington Star,Mary McGrory,1975,no,Mary,mostly_female
116,Correspondence,New York Times,Anne O'Hare McCormick,1937,no,Anne,female
126,Criticism,Los Angeles Times,Mary McNamara,2015,no,Mary,mostly_female
127,Criticism,The Philadelphia Inquirer,Inga Saffron,2014,no,Inga,female
131,Criticism,The Washington Post,Sarah Kaufman,2010,no,Sarah,female
140,Criticism,The Boston Globe,Gail Caldwell,2001,no,Gail,mostly_female
143,Criticism,The New York Times,Michiko Kakutani,1998,no,Michiko,female
146,Criticism,The New York Times,Margo Jefferson,1995,no,Margo,female
...,...,...,...,...,...,...,...
712,Local-Investigative-Specialized-Reporting,The Boston Globe,Joan Vennochi,1980,no,Joan,female
725,Local-Investigative-Specialized-Reporting,The Boston Globe,Ann Desantis,1972,no,Ann,female
741,Local-Reporting,Daily Breeze,Rebecca Kimitch,2015,no,Rebecca,female
749,Local-Reporting,The Patriot-News,Sara Ganim,2012,no,Sara,female
753,Local-Reporting,Milwaukee Journal Sentinel,Raquel Rutledge,2010,no,Raquel,female
760,Local-Reporting,The Miami Herald,Debbie Cenziper,2007,no,Debbie,female
783,Local-Reporting;-No-Edition-Time,The Evening Star,Miriam Ottenberg,1960,no,Miriam,female
792,National-Reporting,The Washington Post,Carol D. Leonnig,2015,no,Carol,mostly_female
795,National-Reporting,InsideClimate News,Elizabeth McGowan,2013,no,Elizabeth,female
796,National-Reporting,InsideClimate News,Lisa Song,2013,no,Lisa,female
820,National-Reporting,The Wall Street Journal,Alix M. Freedman,1996,no,Alix,mostly_female
822,National-Reporting,Albuquerque Tribune,Eileen Welsome,1994,no,Eileen,female
826,National-Reporting,Gannett News Service,Rochelle Sharpe,1991,no,Rochelle,female
829,National-Reporting,The Seattle Times,Mary Ann Gwinn,1990,no,Mary,mostly_female
846,National-Reporting,St. Petersburg (FL) Times,Bette Swenson Orsini,1980,no,Bette,female
859,National-Reporting,United Press International,Lucinda Franks,1971,no,Lucinda,female
889,Newspaper-History-Award,American Press,Minna Lewinson,1918,no,Minna,female
925,Public-Service,Las Vegas Sun,Alexandra Berzon,2009,no,Alexandra,female
936,Public-Service,The Washington Post,Katherine Boo,2000,no,Katherine,female
942,Public-Service,The News & Observer,Melanie Sill,1996,no,Melanie,female
1039,Reporting,The New York Times,Lauren D. Lyman,1936,no,Lauren,mostly_female
1064,Specialized-Reporting,Albuquerque Journal,Tamar Stieber,1990,no,Tamar,female
1068,Specialized-Reporting,Pittsburgh Press,Mary Pat Flaherty,1986,no,Mary,mostly_female
1073,Spot-News-Photography,Pittsburgh Post-Gazette,Martha Rial,1998,no,Martha,female
1074,Spot-News-Photography,The Press Democrat,Annie Wells,1997,no,Annie,female
1076,Spot-News-Photography,The Washington Post,Carol Guzy,1995,no,Carol,mostly_female
1085,Spot-News-Photography,San Francisco Examiner,Kim Komenich,1987,no,Kim,mostly_female
1087,Spot-News-Photography,The Miami Herald,Carol Guzy,1986,no,Carol,mostly_female
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no,Ira,female
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no,Laurence,female

In [86]:
#male winners #698 rows 

df[(df['organizational'] == 'no') & (df['gender'] == 'male') | (df['gender'] == 'mostly_male')]

,category,publication,name,year,organizational,first_name,gender
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no,Daniel,male
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no,David,male
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no,George,male
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no,Michael,male
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no,Chuck,male
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no,Byron,male
11,Beat-Reporting,Newsday,Bob Keeler,1996,no,Bob,male
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no,David,male
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no,Jim,male
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no,Eric,male
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no,Joseph,male
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no,Paul,male
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no,Tyler,mostly_male
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no,Muhammed,male
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no,Khalil,male
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no,Narciso,male
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no,Manu,male
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no,Rodrigo,male
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no,Massoud,male
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no,Ricky,male
31,Breaking-News-Photography,The Miami Herald,Patrick Farrell,2009,no,Patrick,male
33,Breaking-News-Photography,Associated Press,Oded Balilty,2007,no,Oded,male
37,Breaking-News-Photography,The Dallas Morning News,David Leeson,2004,no,David,male
40,Breaking-News-Photography,Associated Press,Alan Diaz,2001,no,Alan,male
61,Commentary,Detroit Free Press,Stephen Henderson,2014,no,Stephen,male
62,Commentary,The Wall Street Journal,Bret Stephens,2013,no,Bret,male
64,Commentary,The New York Times,David Leonhardt,2011,no,David,male
66,Commentary,The Washington Post,Eugene Robinson,2009,no,Eugene,male
67,Commentary,The Washington Post,Steven Pearlstein,2008,no,Steven,male
69,Commentary,The New York Times,Nicholas D. Kristof,2006,no,Nicholas,male
...,...,...,...,...,...,...,...
1084,Spot-News-Photography,Odessa (TX) American,Scott Shaw,1988,no,Scott,male
1086,Spot-News-Photography,The Miami Herald,Michel du Cille,1986,no,Michel,male
1089,Spot-News-Photography,The Boston Globe,Stan Grossfeld,1984,no,Stan,male
1090,Spot-News-Photography,Associated Press,Bill Foley,1983,no,Bill,male
1091,Spot-News-Photography,Associated Press,Ron Edmonds,1982,no,Ron,male
1092,Spot-News-Photography,Fort Worth (TX) Star-Telegram,Larry C. Price,1981,no,Larry,male
1093,Spot-News-Photography,Ettela'at,Jahangir Razmi,1980,no,Jahangir,male
1094,Spot-News-Photography,Pottstown (PA) Mercury,Thomas J. Kelly III,1979,no,Thomas,male
1095,Spot-News-Photography,United Press International,John H. Blair,1978,no,John,male
1096,Spot-News-Photography,Boston Herald American,Stanley Forman,1977,no,Stanley,male
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no,Neal,male
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no,Stanley,male
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no,Gerald,male
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no,Anthony,male
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no,Michel,male
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no,Horst,male
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no,John,male
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no,Steve,male
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no,Edward,male
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no,Rocco,male
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no,Robert,male
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no,Eddy,male
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no,Homer,male
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no,Mark,male
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no,Daniel,male
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no,Edward,male
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no,Edward,male
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no,James,male
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no,Dewey,male
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no,Louis,male

##  <font color = red > ['gender] wrong labeled

In [168]:
#wrong labeling as andy 
import numpy as np
# df.ix[(df['organizational'] == 'yes') & (df['gender'] == 'andy'),'gender'] = np.NaN
df.ix[(df['organizational'] == 'yes') & (df['gender'] == 'andy'),'gender']

19      andy
34      andy
35      andy
39      andy
42      andy
43      andy
44      andy
45      andy
47      andy
48      andy
49      andy
50      andy
51      andy
52      andy
53      andy
54      andy
55      andy
56      andy
57      andy
58      andy
59      andy
370     andy
399     andy
403     andy
422     andy
423     andy
424     andy
441     andy
450     andy
452     andy
        ...
997     andy
998     andy
999     andy
1000    andy
1001    andy
1002    andy
1003    andy
1004    andy
1005    andy
1006    andy
1007    andy
1008    andy
1009    andy
1011    andy
1012    andy
1013    andy
1014    andy
1016    andy
1017    andy
1018    andy
1019    andy
1021    andy
1022    andy
1080    andy
1108    andy
1110    andy
1111    andy
1112    andy
1113    andy
1114    andy
Name: gender, dtype: object

##Create a new copy of df

In [170]:
df2 = df.copy()
df2

,category,publication,name,year,organizational,first_name,gender
0,Beat-Reporting,The Washington Post,Dana Priest,2006,no,Dana,female
1,Beat-Reporting,The Wall Street Journal,Amy Dockser Marcus,2005,no,Amy,female
2,Beat-Reporting,The Wall Street Journal,Daniel Golden,2004,no,Daniel,male
3,Beat-Reporting,The Baltimore Sun,Diana K. Sugg,2003,no,Diana,female
4,Beat-Reporting,The New York Times,Gretchen Morgenson,2002,no,Gretchen,female
5,Beat-Reporting,The New York Times,David Cay Johnston,2001,no,David,male
6,Beat-Reporting,St. Paul Pioneer Press,George Dohrmann,2000,no,George,male
7,Beat-Reporting,Los Angeles Times,Michael A. Hiltzik,1999,no,Michael,male
8,Beat-Reporting,Los Angeles Times,Chuck Philips,1999,no,Chuck,male
9,Beat-Reporting,The New York Times,Linda Greenhouse,1998,no,Linda,female
10,Beat-Reporting,The Seattle Times,Byron Acohido,1997,no,Byron,male
11,Beat-Reporting,Newsday,Bob Keeler,1996,no,Bob,male
12,Beat-Reporting,The Boston Globe,David Shribman,1995,no,David,male
13,Beat-Reporting,The Detroit News,Jim Mitzelfeld,1994,no,Jim,male
14,Beat-Reporting,The Detroit News,Eric Freedman,1994,no,Eric,male
15,Beat-Reporting,The Wall Street Journal,Joseph B. White,1993,no,Joseph,male
16,Beat-Reporting,The Wall Street Journal,Paul Ingrassia,1993,no,Paul,male
17,Beat-Reporting,The Sacramento (CA) Bee,Deborah Blum,1992,no,Deborah,female
18,Beat-Reporting,The New York Times,Natalie Angier,1991,no,Natalie,female
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,andy
20,Breaking-News-Photography,The New York Times,Tyler Hicks,2014,no,Tyler,mostly_male
21,Breaking-News-Photography,Associated Press,Muhammed Muheisen,2013,no,Muhammed,male
22,Breaking-News-Photography,Associated Press,Khalil Hamra,2013,no,Khalil,male
23,Breaking-News-Photography,Associated Press,Narciso Contreras,2013,no,Narciso,male
24,Breaking-News-Photography,Associated Press,Manu Brabo,2013,no,Manu,male
25,Breaking-News-Photography,Associated Press,Rodrigo Abd,2013,no,Rodrigo,male
26,Breaking-News-Photography,Agence France-Presse,Massoud Hossaini,2012,no,Massoud,male
27,Breaking-News-Photography,The Washington Post,Ricky Carioti,2011,no,Ricky,male
28,Breaking-News-Photography,The Washington Post,Nikki Kahn,2011,no,Nikki,female
29,Breaking-News-Photography,The Washington Post,Carol Guzy,2011,no,Carol,mostly_female
...,...,...,...,...,...,...,...
1097,Spot-News-Photography,Associated Press,Neal Ulevich,1977,no,Neal,male
1098,Spot-News-Photography,Boston Herald American,Stanley Forman,1976,no,Stanley,male
1099,Spot-News-Photography,The Seattle Times,Gerald H. Gay,1975,no,Gerald,male
1100,Spot-News-Photography,free-lance photographer,Anthony K. Roberts,1974,no,Anthony,male
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no,Huynh,andy
1102,Spot-News-Photography,Associated Press,Michel Laurent,1972,no,Michel,male
1103,Spot-News-Photography,Associated Press,Horst Faas,1972,no,Horst,male
1104,Spot-News-Photography,Valley Daily News and Daily Dispatch,John Paul Filo,1971,no,John,male
1105,Spot-News-Photography,Associated Press,Steve Starr,1970,no,Steve,male
1106,Spot-News-Photography,Associated Press,Edward T. Adams,1969,no,Edward,male
1107,Spot-News-Photography,Jacksonville Journal,Rocco Morabito,1968,no,Rocco,male
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,andy
1109,Spot-News-Reporting,The New York Times,Robert D. McFadden,1996,no,Robert,male
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,andy
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,andy
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,andy
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,andy
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,andy
1115,Telegraphic-Reporting-(International),Associated Press,Eddy Gilmore,1947,no,Eddy,male
1116,Telegraphic-Reporting-(International),New York Herald Tribune,Homer William Bigart,1946,no,Homer,male
1117,Telegraphic-Reporting-(International),The Baltimore Sun,Mark S. Watson,1945,no,Mark,male
1118,Telegraphic-Reporting-(International),Associated Press,Daniel De Luce,1944,no,Daniel,male
1119,Telegraphic-Reporting-(International),"North American Newspaper Alliance, Inc.",Ira Wolfert,1943,no,Ira,female
1120,Telegraphic-Reporting-(International),Associated Press,Laurence Edmund Allen,1942,no,Laurence,female
1121,Telegraphic-Reporting-(National),The Washington Post,Edward T. Folliard,1947,no,Edward,male
1122,Telegraphic-Reporting-(National),St. Louis Post-Dispatch,Edward A. Harris,1946,no,Edward,male
1123,Telegraphic-Reporting-(National),The New York Times,James B. Reston,1945,no,James,male
1124,Telegraphic-Reporting-(National),The Baltimore Sun,Dewey L. Fleming,1944,no,Dewey,male
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none,NaN,andy
1126,Telegraphic-Reporting-(National),The New York Times,Louis Stark,1942,no,Louis,male

In [176]:
import numpy as np
df2.ix[(df2['organizational'] == 'yes') & (df2['gender'] == 'andy'),'gender'] = np.NaN
df2.ix[(df2['organizational'] == 'yes') & (df2['gender'].notnull())]

Empty DataFrame
Columns: [category, publication, name, year, organizational, first_name, gender]
Index: []

In [179]:
df2[df2['organizational'] == 'yes']

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,NaN
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,NaN
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,NaN
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,NaN
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,NaN
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,NaN
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,NaN
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,NaN
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,NaN
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,NaN
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,NaN
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,NaN
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,NaN
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,NaN
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,NaN
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,NaN
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,NaN
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,NaN
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,NaN
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,NaN
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,NaN
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,NaN
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,NaN
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,NaN
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,NaN
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,NaN
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,NaN
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,NaN
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,NaN
452,Feature-Photography,Associated Press,Staff,1993,yes,NaN,NaN
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,NaN
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,NaN
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,NaN
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,NaN
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,NaN
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,NaN
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,NaN
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,NaN
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,NaN
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,NaN
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,NaN
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,NaN
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,NaN
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,NaN
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,NaN
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,NaN
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,NaN
1016,Public-Service,New York World,New York World,1924,yes,NaN,NaN
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,NaN
1018,Public-Service,New York World,New York World,1922,yes,NaN,NaN
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,NaN
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,NaN
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,NaN
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,NaN
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,NaN
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,NaN
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,NaN
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,NaN
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,NaN
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,NaN

In [185]:
df2[(df2['name'] == 'No Award')]
#f2[df2['gender'] == 'andy'] #df2[df2['organizational'] == 'yes']

,category,publication,name,year,organizational,first_name,gender
149,Criticism,No Award,No Award,1992,none,NaN,andy
214,Editorial-Cartooning,No Award,No Award,1973,none,NaN,andy
222,Editorial-Cartooning,No Award,No Award,1965,none,NaN,andy
227,Editorial-Cartooning,No Award,No Award,1960,none,NaN,andy
251,Editorial-Cartooning,No Award,No Award,1936,none,NaN,andy
264,Editorial-Cartooning,No Award,No Award,1923,none,NaN,andy
295,Editorial-Writing,No Award,No Award,1993,none,NaN,andy
309,Editorial-Writing,No Award,No Award,1981,none,NaN,andy
359,Editorial-Writing,No Award,No Award,1935,none,NaN,andy
362,Editorial-Writing,No Award,No Award,1932,none,NaN,andy
364,Editorial-Writing,No Award,No Award,1930,none,NaN,andy
374,Editorial-Writing,No Award,No Award,1921,none,NaN,andy
376,Editorial-Writing,No Award,No Award,1919,none,NaN,andy
576,International-Reporting,No Award,No Award,1977,none,NaN,andy
883,National-Reporting,No Award,No Award,1951,none,NaN,andy
912,Photography,No Award,No Award,1946,none,NaN,andy
1010,Public-Service,No Award,No Award,1930,none,NaN,andy
1015,Public-Service,No Award,No Award,1925,none,NaN,andy
1020,Public-Service,No Award,No Award,1920,none,NaN,andy
1023,Public-Service,No Award,No Award,1917,none,NaN,andy
1051,Reporting,No Award,No Award,1928,none,NaN,andy
1061,Reporting,No Award,No Award,1919,none,NaN,andy
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none,NaN,andy

In [186]:
df2.ix[(df2['name'] == 'No Award'), 'gender']= np.NaN

In [188]:
df2[df2['name'] == 'No Award']

,category,publication,name,year,organizational,first_name,gender
149,Criticism,No Award,No Award,1992,none,NaN,NaN
214,Editorial-Cartooning,No Award,No Award,1973,none,NaN,NaN
222,Editorial-Cartooning,No Award,No Award,1965,none,NaN,NaN
227,Editorial-Cartooning,No Award,No Award,1960,none,NaN,NaN
251,Editorial-Cartooning,No Award,No Award,1936,none,NaN,NaN
264,Editorial-Cartooning,No Award,No Award,1923,none,NaN,NaN
295,Editorial-Writing,No Award,No Award,1993,none,NaN,NaN
309,Editorial-Writing,No Award,No Award,1981,none,NaN,NaN
359,Editorial-Writing,No Award,No Award,1935,none,NaN,NaN
362,Editorial-Writing,No Award,No Award,1932,none,NaN,NaN
364,Editorial-Writing,No Award,No Award,1930,none,NaN,NaN
374,Editorial-Writing,No Award,No Award,1921,none,NaN,NaN
376,Editorial-Writing,No Award,No Award,1919,none,NaN,NaN
576,International-Reporting,No Award,No Award,1977,none,NaN,NaN
883,National-Reporting,No Award,No Award,1951,none,NaN,NaN
912,Photography,No Award,No Award,1946,none,NaN,NaN
1010,Public-Service,No Award,No Award,1930,none,NaN,NaN
1015,Public-Service,No Award,No Award,1925,none,NaN,NaN
1020,Public-Service,No Award,No Award,1920,none,NaN,NaN
1023,Public-Service,No Award,No Award,1917,none,NaN,NaN
1051,Reporting,No Award,No Award,1928,none,NaN,NaN
1061,Reporting,No Award,No Award,1919,none,NaN,NaN
1125,Telegraphic-Reporting-(National),No Award,No Award,1943,none,NaN,NaN

In [189]:
df2[df2['gender'] == 'andy']

,category,publication,name,year,organizational,first_name,gender
32,Breaking-News-Photography,Reuters,Adrees Latif,2008,no,Adrees,andy
38,Breaking-News-Photography,Rocky Mountain News,Photography Staff,2003,no,Photography,andy
41,Breaking-News-Photography,Rocky Mountain News,Photo Staff,2000,no,Photo,andy
46,Breaking-News-Reporting,No Award,No award,2011,no,No,andy
79,Commentary,New York Daily News,E.R. Shipp,1996,no,E.R.,andy
91,Commentary,The Wall Street Journal,Vermont Royster,1984,no,Vermont,andy
110,Correspondence,The New York Times,Hanson W. Baldwin,1943,no,Hanson,andy
112,Correspondence,None,Group Award,1941,no,Group,andy
123,Correspondence,Philadelphia Public Ledger and New York Evenin...,H. R. Knickerbocker,1931,no,H.,andy
132,Criticism,The New York Times,Holland Cotter,2009,no,Holland,andy
142,Criticism,Chicago Tribune,Blair Kamin,1999,no,Blair,andy
226,Editorial-Cartooning,Chicago Tribune,Carey Orr,1961,no,Carey,andy
242,Editorial-Cartooning,"United Feature Syndicate, Inc.",Sergeant Bill Mauldin,1945,no,Sergeant,andy
250,Editorial-Cartooning,New York Daily News,C.D. Batchelor,1937,no,C.D.,andy
254,Editorial-Cartooning,Washington Daily News,H. M. Talburt,1933,no,H.,andy
261,Editorial-Cartooning,St. Louis Post-Dispatch,D. R. Fitzpatrick,1926,no,D.,andy
267,Editorial-Writing,The Oregonian,Editorial Staff,2014,no,Editorial,andy
270,Editorial-Writing,No Award,No award,2012,no,No,andy
276,Editorial-Writing,No Award,No award,2008,no,No,andy
289,Editorial-Writing,Daily News,Editorial Board,1999,no,Editorial,andy
294,Editorial-Writing,Chicago Tribune,R. Bruce Dold,1994,no,R.,andy
307,Editorial-Writing,The Miami Herald,Miami Herald Editorial Board,1983,no,Miami,andy
318,Editorial-Writing,The Trentonian,F. Gilman Spencer,1974,no,F.,andy
321,Editorial-Writing,The Gainesville (FL) Sun,Horance G. Davis Jr.,1971,no,Horance,andy
332,Editorial-Writing,Norfolk Virginian-Pilot,Lenoir Chambers,1960,no,Lenoir,andy
339,Editorial-Writing,The Wall Street Journal,Vermont Connecticut Royster,1953,no,Vermont,andy
345,Editorial-Writing,Richmond Times-Dispatch,Virginius Dabney,1948,no,Virginius,andy
347,Editorial-Writing,The Delta Democrat-Times,Hodding Carter,1946,no,Hodding,andy
360,Editorial-Writing,Atlantic (IA) News-Telegraph,E. P. Chase,1934,no,E.,andy
361,Editorial-Writing,Kansas City (MO) Star,No author named,1933,no,No,andy
...,...,...,...,...,...,...,...
772,Local-Reporting;-Edition-Time,The Evening Star,Miss Mary Lou Werner,1959,no,Miss,andy
776,Local-Reporting;-Edition-Time,Alice (TX) Daily Echo,Mrs. Caro Brown,1955,no,Mrs.,andy
778,Local-Reporting;-Edition-Time,Providence (RI) Journal and Evening Bulletin,Editorial Staff,1953,no,Editorial,andy
779,Local-Reporting;-No-Edition-Time,Pecos (TX) Independent and Enterprise,NaN,1963,no,nan,andy
804,National-Reporting,The Washington Post,Jo Becker,2008,no,Jo,andy
827,National-Reporting,Gannett News Service,Marjie Lundstrom,1991,no,Marjie,andy
866,National-Reporting,Washington Evening Star,Haynes Johnson,1966,no,Haynes,andy
868,National-Reporting,United Press International,Merriman Smith,1964,no,Merriman,andy
876,National-Reporting,Associated Press,Relman Morin,1958,no,Relman,andy
885,National-Reporting,The New York Times,C. P. Trussell,1949,no,C.,andy
940,Public-Service,The News & Observer,Joby Warrick,1996,no,Joby,andy
941,Public-Service,The News & Observer,Pat Stith,1996,no,Pat,andy
987,Public-Service,"Whiteville News Reporter, Tabor City Tribune",None,1953,no,None,andy
991,Public-Service,Nebraska State Journal,Nebraska State Journa,1949,no,Nebraska,andy
1030,Reporting,New York World-Telegram,Westbrook Pegler,1941,no,Westbrook,andy
1031,Reporting,New York World-Telegram,S. Burton Heath,1940,no,S.,andy
1043,Reporting,Detroit Free Press,J.N.W. Sloan,1932,no,J.N.W.,andy
1044,Reporting,Detroit Free Press,F.D. Webb,1932,no,F.D.,andy
1045,Reporting,Detroit Free Press,J.S. Pooler,1932,no,J.S.,andy
1046,Reporting,Detroit Free Press,D.D. Martin,1932,no,D.D.,andy
1047,Reporting,Detroit Free Press,W.C. Richards,1932,no,W.C.,andy
1048,Reporting,Kansas City (MO) Star,A. B. MacDonald,1931,no,A.,andy
1056,Reporting,San Diego Sun,Magner White,1924,no,Magner,andy
1057,Reporting,The New York Times,Alva Johnston,1923,no,Alva,andy
1058,Reporting,Associated Press,Kirke L. Simpson,1922,no,Kirke,andy
1070,Specialized-Reporting,Macon (GA) Telegraph and News,Jackie Crosby,1985,no,Jackie,andy
1072,Spot-News-Photography,Associated Press,Photo Staff,1999,no,Photo,andy
1082,Spot-News-Photography,The Tribune,Photo Staff,1990,no,Photo,andy
1088,Spot-News-Photography,The Register,Photography Staff,1985,no,Photography,andy
1101,Spot-News-Photography,Associated Press,Huynh Cong Ut,1973,no,Huynh,andy

In [190]:
df2.to_csv('categorization_inprocess2.csv', sep=',', encoding='utf-8')

#========================ignore below===========================

In [ ]:
# No award wrong labeling as andy #['organizational'] == none  # 23 rows 
df[(df['gender'] == 'andy') & (df['name'] == 'No Award')]

In [111]:
# No award wrong labeled as 'andy' #['organizational'] == no #5 rows
temp_df = df[(df['gender'] == 'andy') & (df['organizational'] == 'no')]
temp_df[temp_df['name'] == 'No award']

,category,publication,name,year,organizational,first_name,gender
46,Breaking-News-Reporting,No Award,No award,2011,no,No,andy
270,Editorial-Writing,No Award,No award,2012,no,No,andy
276,Editorial-Writing,No Award,No award,2008,no,No,andy
480,Feature-Writing,No Award,No award,2014,no,No,andy
490,Feature-Writing,No Award,No award,2004,no,No,andy

In [ ]:
# indie
df['gender'] == 'female'|df['gender'] == 'mostly_female' & .value_counts()

#Dealing with missing data

In [268]:
import numpy as np
df['first_name'][38] = np.nan  #assign missing data

/Users/Spepe/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app

In [293]:
#problem = [38,41, 267,289,446,467,678,778,1072,1082,1088]
df

TypeError: cannot convert the series to <type 'float'>

TypeError: cannot convert the series to <type 'float'>

In [283]:
df['first_name'][1082]

'No'

In [269]:
df[35:40]

,category,publication,name,year,organizational,first_name,gender
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,NaN
36,Breaking-News-Photography,The Dallas Morning News,Cheryl Diaz Meyer,2004,no,Cheryl,female
37,Breaking-News-Photography,The Dallas Morning News,David Leeson,2004,no,David,male
38,Breaking-News-Photography,Rocky Mountain News,Photography Staff,2003,yes,NaN,andy
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,NaN

In [260]:
df[(df['first_name'].isnull()) & (df['organizational'] == 'yes')]

,category,publication,name,year,organizational,first_name,gender
19,Breaking-News-Photography,St. Louis Post-Dispatch,Staff,2015,yes,NaN,NaN
34,Breaking-News-Photography,The Dallas Morning News,Staff,2006,yes,NaN,NaN
35,Breaking-News-Photography,Associated Press,Staff,2005,yes,NaN,NaN
39,Breaking-News-Photography,The New York Times,Staff,2002,yes,NaN,NaN
42,Breaking-News-Reporting,The Seattle Times,Staff,2015,yes,NaN,NaN
43,Breaking-News-Reporting,The Boston Globe,Staff,2014,yes,NaN,NaN
44,Breaking-News-Reporting,The Denver Post,Staff,2013,yes,NaN,NaN
45,Breaking-News-Reporting,The Tuscaloosa (Ala.) News,Staff,2012,yes,NaN,NaN
47,Breaking-News-Reporting,The Seattle Times,Staff,2010,yes,NaN,NaN
48,Breaking-News-Reporting,The New York Times,Staff,2009,yes,NaN,NaN
49,Breaking-News-Reporting,The Washington Post,Staff,2008,yes,NaN,NaN
50,Breaking-News-Reporting,The Oregonian,Staff,2007,yes,NaN,NaN
51,Breaking-News-Reporting,The Times-Picayune,Staff,2006,yes,NaN,NaN
52,Breaking-News-Reporting,The Star-Ledger,Staff,2005,yes,NaN,NaN
53,Breaking-News-Reporting,Los Angeles Times,Staff,2004,yes,NaN,NaN
54,Breaking-News-Reporting,The Eagle-Tribune,Staff,2003,yes,NaN,NaN
55,Breaking-News-Reporting,The Wall Street Journal,Staff,2002,yes,NaN,NaN
56,Breaking-News-Reporting,The Miami Herald,Staff,2001,yes,NaN,NaN
57,Breaking-News-Reporting,The Denver Post,Staff,2000,yes,NaN,NaN
58,Breaking-News-Reporting,Hartford (CT) Courant,Staff,1999,yes,NaN,NaN
59,Breaking-News-Reporting,Los Angeles Times,Staff,1998,yes,NaN,NaN
370,Editorial-Writing,The Boston Herald,The Boston Herald,1924,yes,NaN,NaN
399,Explanatory-Journalism,The New York Times,Staff,1986,yes,NaN,NaN
403,Explanatory-Reporting,The New York Times,Staff,2013,yes,NaN,NaN
410,Explanatory-Reporting,The New York Times,staff,2010,yes,NaN,NaN
422,Explanatory-Reporting,The Wall Street Journal,Staff,2003,yes,NaN,NaN
423,Explanatory-Reporting,The New York Times,Staff,2002,yes,NaN,NaN
424,Explanatory-Reporting,Chicago Tribune,Staff,2001,yes,NaN,NaN
441,Feature-Photography,The New York Times,Staff,2002,yes,NaN,NaN
450,Feature-Photography,Associated Press,Staff,1995,yes,NaN,NaN
...,...,...,...,...,...,...,...
997,Public-Service,Omaha (NE) World-Herald,Omaha (NE) World-Herald,1943,yes,NaN,NaN
998,Public-Service,Los Angeles Times,Los Angeles Times,1942,yes,NaN,NaN
999,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1941,yes,NaN,NaN
1000,Public-Service,Waterbury (CT) Republican & American,Waterbury (CT) Republican & American,1940,yes,NaN,NaN
1001,Public-Service,Miami Daily News,Miami Daily News,1939,yes,NaN,NaN
1002,Public-Service,Bismarck (ND) Tribune,Bismarck (ND) Tribune,1938,yes,NaN,NaN
1003,Public-Service,St. Louis Post-Dispatch,St. Louis Post-Dispatch,1937,yes,NaN,NaN
1004,Public-Service,Cedar Rapids Gazette,Cedar Rapids Gazette,1936,yes,NaN,NaN
1005,Public-Service,The Sacramento (CA) Bee,The Sacramento (CA) Bee,1935,yes,NaN,NaN
1006,Public-Service,Medford (OR) Mail Tribune,Medford (OR) Mail Tribune,1934,yes,NaN,NaN
1007,Public-Service,New York World-Telegram,New York World-Telegram,1933,yes,NaN,NaN
1008,Public-Service,Indianapolis News,Indianapolis News,1932,yes,NaN,NaN
1009,Public-Service,The Atlanta Constitution,The Atlanta Constitution,1931,yes,NaN,NaN
1011,Public-Service,New York Evening World,New York Evening World,1929,yes,NaN,NaN
1012,Public-Service,The Indianapolis Times,The Indianapolis Times,1928,yes,NaN,NaN
1013,Public-Service,Canton (Ohio) Daily News,Canton (Ohio) Daily News,1927,yes,NaN,NaN
1014,Public-Service,Columbus (GA) Enquirer Sun,Columbus (GA) Enquirer Sun,1926,yes,NaN,NaN
1016,Public-Service,New York World,New York World,1924,yes,NaN,NaN
1017,Public-Service,Memphis Commercial Appeal,Memphis Commercial Appeal,1923,yes,NaN,NaN
1018,Public-Service,New York World,New York World,1922,yes,NaN,NaN
1019,Public-Service,The Boston Post,The Boston Post,1921,yes,NaN,NaN
1021,Public-Service,The Milwaukee Journal,The Milwaukee Journal,1919,yes,NaN,NaN
1022,Public-Service,The New York Times,The New York Times,1918,yes,NaN,NaN
1080,Spot-News-Photography,Associated Press,Staff,1992,yes,NaN,NaN
1108,Spot-News-Reporting,Newsday,Staff,1997,yes,NaN,NaN
1110,Spot-News-Reporting,Los Angeles Times,Staff,1995,yes,NaN,NaN
1111,Spot-News-Reporting,The New York Times,Staff,1994,yes,NaN,NaN
1112,Spot-News-Reporting,Los Angeles Times,Staff,1993,yes,NaN,NaN
1113,Spot-News-Reporting,Newsday,Staff,1992,yes,NaN,NaN
1114,Spot-News-Reporting,The Miami Herald,Staff,1991,yes,NaN,NaN